var app = new Vue({
    el:'#app',
    data:{
        saludo:'Hello world from Vuejs',
        fruits:[
            {
            'name':'apple',
            'cantidad':10
            },
            {
            'name':'banana',
            'cantidad':3
            },
            {
            'name':'orange',
            'cantidad':0
            }
        ],
        newFruit:''
    },
    methods:{
        addFruit(){
            this.fruits.push({
                name:this.newFruit,
                cantidad:0
            })
        }
    }
})